command:
  - "python"
  - "app.py"
env:
  - name: SERVING_ENDPOINT
    value: "databricks-gpt-5-mini"
  - name: VS_ENDPOINT_NAME
    value: "exam-bot-vs-endpoint"
  - name: VS_INDEX_NAME
    value: "exam_qa_bot.default.docs_chunks_index"
